name: Build project

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      # - name: Test
        # run: xcodebuild test -target "cryptoPass (iOS)" -scheme "cryptoPass (iOS)" -destination "platform=iOS Simulator" | xcpretty  && exit ${PIPESTATUS[0]}
      # - name: Build
        # run: xcodebuild build test -target "cryptoPass (iOS)" -scheme "cryptoPass (iOS)" -destination "generic/platform=iOS" | xcpretty  && exit ${PIPESTATUS[0]}
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ (github.event.pusher.name != 'github action') && (github.ref == 'refs/heads/main') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          branch: main